name: deploy

on:
  push: [tags]
  repository_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow
      - name: Checkout latest tags
        run: |
          git checkout $(git describe --tags --abbrev=0)
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
        env:
          GRIDSOME_CONTENTFUL_SPACE_ID: ${{ secrets.GRIDSOME_CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          GRIDSOME_CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.GRIDSOME_CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
